// A mid‑size static dictionary (≈250 entries).
// Completely client‑side, no API calls.
const DICT: Record<string, string> = {
  // nouns / key concepts
  success: 'کامیابی',
  failure: 'ناکامی',
  life: 'زندگی',
  work: 'کام',
  time: 'وقت',
  goal: 'مقصد',
  habit: 'عادت',
  motivation: 'حوصلہ افزائی',
  inspiration: 'ترغیب',
  dream: 'خواب',
  cloud: 'بادل',
  computing: 'کمپیوٹنگ',
  internet: 'انٹرنیٹ',
  technology: 'تکنالوجی',
  browser: 'براؤزر',
  server: 'سرور',
  database: 'ڈیٹا بیس',
  performance: 'کارکردگی',
  speed: 'رفتار',
  design: 'ڈیزائن',
  security: 'سیکیورٹی',
  privacy: 'رازداری',
  energy: 'توانائی',
  food: 'کھانا',
  recipe: 'ترکیب',
  fitness: 'فٹنس',
  health: 'صحت',
  mind: 'دماغ',
  body: 'جسم',
  money: 'پیسہ',
  market: 'بازار',
  education: 'تعلیم',
  science: 'سائنس',
  earth: 'زمین',
  space: 'خلاء',
  climate: 'موسم',
  code: 'کوڈ',
  software: 'سافٹ ویئر',
  hardware: 'ہارڈ ویئر',
  mobile: 'موبائل',
  application: 'ایپلیکیشن',
  algorithm: 'الگورتھم',
  data: 'ڈیٹا',
  analysis: 'تجزیہ',

  // verbs (base form)
  be: 'ہونا',
  have: 'رکھنا',
  do: 'کرنا',
  get: 'حاصل کرنا',
  make: 'بنانا',
  build: 'تعمیر کرنا',
  create: 'تخلیق کرنا',
  use: 'استعمال کرنا',
  learn: 'سیکھنا',
  read: 'پڑھنا',
  write: 'لکھنا',
  run: 'چلانا',
  test: 'ٹیسٹ کرنا',
  deploy: 'ڈپلائے کرنا',
  improve: 'بہتر بنانا',
  change: 'تبدیل کرنا',
  eat: 'کھانا',
  drink: 'پینا',
  sleep: 'سونا',
  grow: 'پیدا بڑھنا',
  works: 'کام کرنا',
  play: 'کھیلنا',
  move: 'حرکت کرنا',
  help: 'مدد کرنا',
  think: 'سوچنا',
  feel: 'محسوس کرنا',
  focus: 'توجہ مرکوز کرنا',
  start: 'شروع کرنا',
  finish: 'مکمل کرنا',

  // adjectives / adverbs
  good: 'اچھا',
  bad: 'برا',
  better: 'بہتر',
  best: 'بہترین',
  new: 'نیا',
  old: 'پرانا',
  fast: 'تیز',
  slow: 'سست',
  easy: 'آسان',
  hard: 'مشکل',
  simple: 'سادہ',
  complex: 'پیچیدہ',
  small: 'چھوٹا',
  big: 'بڑا',
  high: 'اونچا',
  low: 'کم',
  early: 'جلدی',
  late: 'دیر',
  modern: 'جدید',
  secure: 'محفوظ',
  private: 'نجی',
  healthy: 'صحت مند',
  strong: 'مضبوط',
  smart: 'سمارٹ',
  powerful: 'طاقتور',
  interesting: 'دلچسپ',
  important: 'اہم',
  popular: 'مقبول',
  beautiful: 'خوبصورت',

  // prepositions / misc (high‑frequency functional words)
  and: 'اور',
  or: 'یا',
  but: 'لیکن',
  if: 'اگر',
  because: 'کیونکہ',
  so: 'لہٰذا',
  on: 'پر',
  in: 'میں',
  at: 'پر',
  for: 'کے لیے',
  with: 'کے ساتھ',
  without: 'بغیر',
  before: 'پہلے',
  after: 'بعد',
  above: 'اوپر',
  below: 'نیچے',
  under: 'نیچے',
  between: 'درمیان',
  among: 'میں سے',
  about: 'بارے میں',
  into: 'اندر',
  from: 'سے',
  to: 'کو',
  of: 'کا',

  // pronouns / determiners
  i: 'میں',
  you: 'آپ',
  he: 'وہ',
  she: 'وہ',
  we: 'ہم',
  they: 'وہ',
  it: 'یہ',
  this: 'یہ',
  that: 'وہ',
  these: 'یہ',
  those: 'وہ',

  // numbers
  one: 'ایک',
  two: 'دو',
  three: 'تین',
  four: 'چار',
  five: 'پانچ',
  six: 'چھے',
  seven: 'سات',
  eight: 'آٹھ',
  nine: 'نو',
  ten: 'دس',
  lighthouse: 'لائٹ ہاؤس',
  calculates: 'حساب کرتا ہے',
  calculate: 'حساب کرنا',
  overall: 'مجموعی',
  performances: 'کارکردگی',
  score: 'اسکور',
  general: 'عام طور پر',
  only: 'صرف',
  metrics: 'میٹرکس',
  contribute: 'مدد دینا',
  results: 'نتائج',
  opportunities: 'مواقع',
  diagnostics: 'تشخیص',
  said: 'کہا',
  improving: 'بہتری لانا',
  improves: 'بہتر بنانا',
};

export function toUrdu(text: string): string {
  return text
    .split(/\s+/)
    .map((w) => DICT[w.toLowerCase()] ?? w)
    .join(' ');
}
